apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: webapp
build:
  artifacts:
  - image: deva-groupe8-k3s:5000/webapp-example
    context: app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/webapp.yml
