name: Build and push Docker image

on:
  push:
    branches:
      - main
      - skaffoldbuildimage

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: deva-groupe8-k3s/webapp-example
  IMAGE_TAG: 7f6a852-dirty

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the docker Docker image
      run: |
       docker build . --tag ghcr.io/lululazone/webapp-example:latest
       docker run ghcr.io/lululazone/webapp-example:latest
       docker push ghcr.io/lululazone/webapp-example:latest
       
    - name: Deploy to the Kubernetes cluster
      uses: azure/k8s-deploy@v1
      with:
          namespace: default
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/ingress.yaml
            kubernetes/service.yaml
          images: |
            ghcr.io/lululazone/package:${{ github.sha }}


